//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnlaceVA.Tests.Utterances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralUtterances {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralUtterances() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnlaceVA.Tests.Utterances.GeneralUtterances", typeof(GeneralUtterances).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono a tu factura.
        /// </summary>
        internal static string Abona_a_tu_factura {
            get {
                return ResourceManager.GetString("Abona_a_tu_factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adquirir un seguro con brilla.
        /// </summary>
        internal static string Adquiere_tu_seguro {
            get {
                return ResourceManager.GetString("Adquiere_tu_seguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cambiar el nombre del titular.
        /// </summary>
        internal static string Cambio_de_nombre {
            get {
                return ResourceManager.GetString("Cambio_de_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel it.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gdo.
        /// </summary>
        internal static string CompanyTest {
            get {
                return ResourceManager.GetString("CompanyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constancia de pago de los meses.
        /// </summary>
        internal static string Constancia_de_pago {
            get {
                return ResourceManager.GetString("Constancia_de_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consumo facturado.
        /// </summary>
        internal static string Consumo_facturado {
            get {
                return ResourceManager.GetString("Consumo_facturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puedo trasladar mi servicio.
        /// </summary>
        internal static string DebtTransfer {
            get {
                return ResourceManager.GetString("DebtTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traslado deuda brilla.
        /// </summary>
        internal static string DebtTransferSecond {
            get {
                return ResourceManager.GetString("DebtTransferSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daño en la red.
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectarme al agua.
        /// </summary>
        internal static string ErrorQuestion {
            get {
                return ResourceManager.GetString("ErrorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can i talk to a person.
        /// </summary>
        internal static string Escalate {
            get {
                return ResourceManager.GetString("Escalate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estado de solicitud pqr.
        /// </summary>
        internal static string Estado_de_solicitud_PQRs {
            get {
                return ResourceManager.GetString("Estado_de_solicitud_PQRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to como me pueden exonerar de la contribución.
        /// </summary>
        internal static string Exemption {
            get {
                return ResourceManager.GetString("Exemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industria no regulada.
        /// </summary>
        internal static string ExemptionSecond {
            get {
                return ResourceManager.GetString("ExemptionSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string FeedbackScore {
            get {
                return ResourceManager.GetString("FeedbackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all finished.
        /// </summary>
        internal static string FinishTask {
            get {
                return ResourceManager.GetString("FinishTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brilla y seguros.
        /// </summary>
        internal static string MenuBrilla {
            get {
                return ResourceManager.GetString("MenuBrilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brilla es un cupo para comprar lo que quieras.
        /// </summary>
        internal static string QnAAnswer {
            get {
                return ResourceManager.GetString("QnAAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupo Brilla.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could you say it again.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any one is ok.
        /// </summary>
        internal static string SelectAny {
            get {
                return ResourceManager.GetString("SelectAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose the last one.
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none of them.
        /// </summary>
        internal static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string ShowNext {
            get {
                return ResourceManager.GetString("ShowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        internal static string ShowPrevious {
            get {
                return ResourceManager.GetString("ShowPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        internal static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be quiet.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to como puedo terminar mi contrato.
        /// </summary>
        internal static string Terminación_de_contrato {
            get {
                return ResourceManager.GetString("Terminación_de_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuándo se vence mi factura.
        /// </summary>
        internal static string Valor_fecha_limite_y_referencia_pago {
            get {
                return ResourceManager.GetString("Valor_fecha_limite_y_referencia_pago", resourceCulture);
            }
        }
    }
}
