//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnlaceVA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponsesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponsesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnlaceVA.Resources.ResponsesResource", typeof(ResponsesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                  &quot;title&quot;: &quot;Cédula de ciudadanía&quot;,
        ///                  &quot;value&quot;: &quot;111&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Pasaporte&quot;,
        ///                  &quot;value&quot;: &quot;112&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Cédula de extranjería&quot;,
        ///                  &quot;value&quot;: &quot;113&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Tarjeta de identidad&quot;,
        ///                  &quot;value&quot;: &quot;114&quot;
        ///                },                
        ///                {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TICeo {
            get {
                return ResourceManager.GetString("TICeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {
        ///                  &quot;title&quot;: &quot;Cédula de ciudadanía&quot;,
        ///                  &quot;value&quot;: &quot;1&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Pasaporte&quot;,
        ///                  &quot;value&quot;: &quot;2&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Cédula de extranjería&quot;,
        ///                  &quot;value&quot;: &quot;3&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;Tarjeta de identidad&quot;,
        ///                  &quot;value&quot;: &quot;4&quot;
        ///                },                
        ///                {
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TIGdoStg {
            get {
                return ResourceManager.GetString("TIGdoStg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                  &quot;title&quot;: &quot;DNI&quot;,
        ///                  &quot;value&quot;: &quot;2&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;CARNÉ DE EXTRANJERIA&quot;,
        ///                  &quot;value&quot;: &quot;3&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;RUC&quot;,
        ///                  &quot;value&quot;: &quot;6&quot;
        ///                },
        ///                {
        ///                  &quot;title&quot;: &quot;PASAPORTE&quot;,
        ///                  &quot;value&quot;: &quot;7&quot;
        ///                }.
        /// </summary>
        public static string TIQuavii {
            get {
                return ResourceManager.GetString("TIQuavii", resourceCulture);
            }
        }
    }
}
