//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnlaceVA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrlsCompanies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrlsCompanies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnlaceVA.Resources.UrlsCompanies", typeof(UrlsCompanies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ConceptoFactura_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConceptoFacturaCEO {
            get {
                return ResourceManager.GetString("ConceptoFacturaCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConceptoFactura_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConceptoFacturaGDO {
            get {
                return ResourceManager.GetString("ConceptoFacturaGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ConceptoFactura_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConceptoFacturaQUAVII {
            get {
                return ResourceManager.GetString("ConceptoFacturaQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConceptoFactura_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConceptoFacturaSTG {
            get {
                return ResourceManager.GetString("ConceptoFacturaSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaCupoBrilla_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaCupoBrillaCEO {
            get {
                return ResourceManager.GetString("ConsultaCupoBrillaCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaCupoBrilla_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaCupoBrillaGDO {
            get {
                return ResourceManager.GetString("ConsultaCupoBrillaGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaCupoBrilla_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaCupoBrillaQUAVII {
            get {
                return ResourceManager.GetString("ConsultaCupoBrillaQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_STG&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaCupoBrilla_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaCupoBrillaSTG {
            get {
                return ResourceManager.GetString("ConsultaCupoBrillaSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaEstado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaPQRCEO {
            get {
                return ResourceManager.GetString("ConsultaPQRCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaEstado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaPQRGDO {
            get {
                return ResourceManager.GetString("ConsultaPQRGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaEstado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaPQRQUAVII {
            get {
                return ResourceManager.GetString("ConsultaPQRQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaEstado_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsultaPQRSTG {
            get {
                return ResourceManager.GetString("ConsultaPQRSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ConsumoFacturado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsumoFacturadoCEO {
            get {
                return ResourceManager.GetString("ConsumoFacturadoCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConsumoFacturado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsumoFacturadoGDO {
            get {
                return ResourceManager.GetString("ConsumoFacturadoGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ConsumoFacturado_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsumoFacturadoQUAVII {
            get {
                return ResourceManager.GetString("ConsumoFacturadoQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=ConsumoFacturado_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ConsumoFacturadoSTG {
            get {
                return ResourceManager.GetString("ConsumoFacturadoSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=OSMFLEX_CEO&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=CuponPagoParcial_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string CuponPagoParcialCEO {
            get {
                return ResourceManager.GetString("CuponPagoParcialCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=GDOCHATBOT_D&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=CuponPagoParcial_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string CuponPagoParcialGDO {
            get {
                return ResourceManager.GetString("CuponPagoParcialGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=OSMFLEX_GDP&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=CuponPagoParcial_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string CuponPagoParcialQAVII {
            get {
                return ResourceManager.GetString("CuponPagoParcialQAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=STGCHATBOT_D&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=CuponPagoParcial_Out&amp;amp;interfaceNamespace=urn%3Agaseras.stg.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string CuponPagoParcialSTG {
            get {
                return ResourceManager.GetString("CuponPagoParcialSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=CEOCHATBOT_Q&amp;receiverParty=&amp;receiverService=&amp;interface=EstadoCuenta_Out&amp;interfaceNamespace=urn:gaseras.ceoc.com:srvemp:bss:chatbot.
        /// </summary>
        public static string EstadoCuentaCEO {
            get {
                return ResourceManager.GetString("EstadoCuentaCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=EstadoCuenta_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string EstadoCuentaGDO {
            get {
                return ResourceManager.GetString("EstadoCuentaGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDPCHATBOT_Q&amp;receiverParty=&amp;receiverService=&amp;interface=EstadoCuenta_Out&amp;interfaceNamespace=urn:gaseras.gdp.com:srvemp:bss:chatbot.
        /// </summary>
        public static string EstadoCuentaQUAVII {
            get {
                return ResourceManager.GetString("EstadoCuentaQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=EstadoCuenta_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string EstadoCuentaSTG {
            get {
                return ResourceManager.GetString("EstadoCuentaSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ReconexionServicioPago_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ReconexionPorPagoCEO {
            get {
                return ResourceManager.GetString("ReconexionPorPagoCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=ReconexionServicioPago_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ReconexionPorPagoGDO {
            get {
                return ResourceManager.GetString("ReconexionPorPagoGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ReconexionServicioPago_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ReconexionPorPagoQUAVII {
            get {
                return ResourceManager.GetString("ReconexionPorPagoQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_STG&amp;receiverParty=&amp;receiverService=&amp;interface=ReconexionServicioPago_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ReconexionPorPagoSTG {
            get {
                return ResourceManager.GetString("ReconexionPorPagoSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=OSMFLEX_CEO&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=ConsultaSaldoPendiente_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string SaldoPendienteCEO {
            get {
                return ResourceManager.GetString("SaldoPendienteCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=ConsultaSaldoPendiente_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string SaldoPendienteGDO {
            get {
                return ResourceManager.GetString("SaldoPendienteGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=OSMFLEX_GDP&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=ConsultaSaldoPendiente_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string SaldoPendienteQUAVII {
            get {
                return ResourceManager.GetString("SaldoPendienteQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;amp;senderService=OSMFLEX_STG&amp;amp;receiverParty=&amp;amp;receiverService=&amp;amp;interface=ConsultaSaldoPendiente_Out&amp;amp;interfaceNamespace=urn%3Agaseras.com%3Asrvemp%3Abss%3Achatbot.
        /// </summary>
        public static string SaldoPendienteSTG {
            get {
                return ResourceManager.GetString("SaldoPendienteSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=CEOCHATBOT_Q&amp;receiverParty=&amp;receiverService=&amp;interface=TomaLectura_Out&amp;interfaceNamespace=urn:gaseras.ceoc.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TomaLecturaCEO {
            get {
                return ResourceManager.GetString("TomaLecturaCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=TomaLectura_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TomaLecturaGDO {
            get {
                return ResourceManager.GetString("TomaLecturaGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDPCHATBOT_Q&amp;receiverParty=&amp;receiverService=&amp;interface=TomaLectura_Out&amp;interfaceNamespace=urn:gaseras.gdp.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TomaLecturaQUAVII {
            get {
                return ResourceManager.GetString("TomaLecturaQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=TomaLectura_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TomaLecturaSTG {
            get {
                return ResourceManager.GetString("TomaLecturaSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=TratamientoDatos_CEO_QUAVII_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TratamientoDatosCEO {
            get {
                return ResourceManager.GetString("TratamientoDatosCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=TratamientoDatos_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TratamientoDatosGDO {
            get {
                return ResourceManager.GetString("TratamientoDatosGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=TratamientoDatos_CEO_QUAVII_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TratamientoDatosQUAVII {
            get {
                return ResourceManager.GetString("TratamientoDatosQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_STG&amp;receiverParty=&amp;receiverService=&amp;interface=TratamientoDatos_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string TratamientoDatosSTG {
            get {
                return ResourceManager.GetString("TratamientoDatosSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace EnlaceVA.Resources {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-ty [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UrlsCompanies_Designer {
            get {
                return ResourceManager.GetString("UrlsCompanies_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:gaseras.com:srvemp:chatbot.
        /// </summary>
        public static string UrnGeneral {
            get {
                return ResourceManager.GetString("UrnGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarCliente_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarClienteCEO {
            get {
                return ResourceManager.GetString("ValidarClienteCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarCliente_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarClienteGDO {
            get {
                return ResourceManager.GetString("ValidarClienteGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarCliente_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarClienteQUAVII {
            get {
                return ResourceManager.GetString("ValidarClienteQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_STG&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarCliente_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarClienteSTG {
            get {
                return ResourceManager.GetString("ValidarClienteSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_CEO&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarContrato_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarContratoCEO {
            get {
                return ResourceManager.GetString("ValidarContratoCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDO&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarContrato_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarContratoGDO {
            get {
                return ResourceManager.GetString("ValidarContratoGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_GDP&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarContrato_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarContratoQUAVII {
            get {
                return ResourceManager.GetString("ValidarContratoQUAVII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=OSMFLEX_STG&amp;receiverParty=&amp;receiverService=&amp;interface=ValidarContrato_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string ValidarContratoSTG {
            get {
                return ResourceManager.GetString("ValidarContratoSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=VentaSeguros_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string VentaSegurosGDO {
            get {
                return ResourceManager.GetString("VentaSegurosGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=VentaSeguros_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string VentaSegurosSTG {
            get {
                return ResourceManager.GetString("VentaSegurosSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=GDOCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=VisitaFinNoBanca_Out&amp;interfaceNamespace=urn:gaseras.com:srvemp:bss:chatbot.
        /// </summary>
        public static string VisitaFinNoBancaGDO {
            get {
                return ResourceManager.GetString("VisitaFinNoBancaGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://servicios.enlacecsc.com/chatbotDEV/MessageServlet?senderParty=&amp;senderService=STGCHATBOT_D&amp;receiverParty=&amp;receiverService=&amp;interface=VisitaFinNoBanca_Out&amp;interfaceNamespace=urn:gaseras.stg.com:srvemp:bss:chatbot.
        /// </summary>
        public static string VisitaFinNoBancaSTG {
            get {
                return ResourceManager.GetString("VisitaFinNoBancaSTG", resourceCulture);
            }
        }
    }
}
